### ISSUE TITLE
Connection fails on sites with self-signed certificate

### ISSUE THREAD

**Issue by midwan** [Mouaijin/SubsonicSharp#4]
I noticed that the connection fails (even the unit tests, e.g. Ping) if the Subsonic server is using a self-signed certificate.

When running the PingTest() Unit test, these are the results in such a scenario:
Test Name:	PingTest
Test FullName:	Tests.ConnectionTests.PingTest
Test Source:	D:\midwa\Projects\GitHub\SubsonicSharp\Tests\ConnectionTests.cs : line 35
Test Outcome:	Failed
Test Duration:	0:00:01.7347063

```
Result StackTrace:	
at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
 --- End of inner exception stack trace ---
    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
 --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at SubsonicSharp.SubsonicClient.GetResponse(RestCommand command, String caller) in D:\midwa\Projects\GitHub\SubsonicSharp\SubsonicSharp\SubsonicClient.cs:line 73
   at SubsonicSharp.SubsonicClient.GetResponseXDocument(RestCommand command, String caller) in D:\midwa\Projects\GitHub\SubsonicSharp\SubsonicSharp\SubsonicClient.cs:line 90
   at SubsonicSharp.SubsonicClient.PingServer() in D:\midwa\Projects\GitHub\SubsonicSharp\SubsonicSharp\SubsonicClient.cs:line 118
   at Tests.ConnectionTests.PingTest() in D:\midwa\Projects\GitHub\SubsonicSharp\Tests\ConnectionTests.cs:line 36
Result Message:	
Test method Tests.ConnectionTests.PingTest threw exception: 
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
```

This seems to be coming from the HttpClient class, which by default does not like self-signed certificates.

Have you considered using something like RestSharp (http://restsharp.org/) for the actual REST calls? I found that it simplifies the syntax quite a lot, and as a bonus, does not suffer from this problem with self-signed certs either.

**Comment by Mouaijin** [comment]
I did originally consider using RestSharp, but since this project is built as a PCL and RS uses standard .Net, it was impossible to utilize without compromising compatibility.
Since we have the SubsonicClient set up for HTTPS now, it should be possible to write a workaround for this without the need for external dependencies or totally dangerous code.
I'm taking a look now at a possible solution.

**Comment by Mouaijin** [comment]
Okay, so here's what I've found: there isn't a way to fix the behavior *within the PCL*.
The way to get around this is to add the following line of code to the project consuming this library, somewhere before instantiating a SubsonicClient object.
`ServicePointManager.ServerCertificateValidationCallback = (sender, certificate, chain, errors) => true;`
I would recommend resetting this callback to null on completion of a request, as it will trust any SSL certificate, or modifying it as needed to actually authenticate the cert.
For some reason, there is no way to access SSL certificate authentication controls from any PCL implementations of HttpClient, WebRequest, etc. The real solution here is to include an Http handler interface, and then rely on dependency injection for each version of .Net to give this SSL functionality, but I have neither the time nor patience to actually write out the projects and tests for Android, iOS, WP, .Net full, Xamarin Forms, etc. alone.

I will update the "documentation" to reflect this workaround for HTTPS, as it will be the same regardless of the trust level of the certificate.
